import json
from harness import *; from fixtures import *
serve()
R=[]
def ok(n,c,d=''):
    R.append(bool(c));print(('PASS ' if c else 'FAIL ')+n+('' if c else '  -> '+str(d)))
def sync(src,dst):
    dst.evaluate("(d)=>{for(const k of ['auction_state','auction_unsold','team_season_rosters']){__DB[k].length=0;for(const r of d[k])__DB[k].push(r);}}",src.evaluate("({auction_state:__DB.auction_state,auction_unsold:__DB.auction_unsold,team_season_rosters:__DB.team_season_rosters})"))
with sync_playwright() as pw:
    sa=Site(pw,scenario_auction(),admin=True);adm=sa.page('auction.html',1200)
    sv=Site(pw,scenario_auction(),admin=False);vw=sv.page('auction.html',1200)
    ok('no JS errors (admin+viewer)',not adm.errs and not vw.errs,(adm.errs,vw.errs))
    ok('viewer: wheel is visible to everyone',vw.is_visible('#wheel') and vw.is_visible('.wheel-pointer'))
    ok('viewer: no spin/sold buttons',not vw.is_visible('#btn-spin') and not vw.is_visible('#sell-panel'))
    ok('wheel has only non-owners (5), owners excluded (both screens)',adm.evaluate('wheelNames.length')==5 and vw.evaluate('wheelNames.length')==5 and not any(n in vw.evaluate('wheelNames') for n in ['Nasiq','Amritpal Singh','Bhagyesh Rane','Varun']),vw.evaluate('wheelNames'))
    ok('admin: Round 2 button hidden while Round 1 has players',not adm.is_visible('#btn-load-r2'))
    # ---- spin: admin publishes, viewer replays same spin ----
    adm.click('#btn-spin');adm.wait_for_timeout(600)
    st=adm.evaluate("__DB.auction_state[0]")
    ok('spin published: pool of 5, winner in pool, seq 1',st['spin_seq']==1 and len(st['spin_pool'])==5 and st['spin_winner_id'] in st['spin_pool'],st)
    sync(adm,vw);vw.wait_for_timeout(2600)      # viewer's light poll notices the new spin
    ok('viewer: animating the same spin (wheel names = admin pool, "Spinning…", winner hidden until stop)',vw.evaluate('ANIM')==True and 'Spinning' in vw.inner_text('#on-block'),(vw.evaluate('ANIM'),vw.inner_text('#on-block')))
    adm.wait_for_timeout(6500);vw.wait_for_timeout(4200)
    winner=st['spin_winner_id'];wname=adm.evaluate("(id)=>PLAYERS[id].full_name",winner)
    ok('after spin: winner shown on block on BOTH screens',wname in adm.inner_text('#on-block') and wname in vw.inner_text('#on-block'),(adm.inner_text('#on-block'),vw.inner_text('#on-block')))
    ok('picked player removed from wheel immediately (4 left) on both screens',adm.evaluate('wheelNames.length')==4 and vw.evaluate('wheelNames.length')==4 and wname not in vw.evaluate('wheelNames'),(adm.evaluate('wheelNames'),vw.evaluate('wheelNames')))
    ok('pointer geometry: spin lands exactly on the winner segment',adm.evaluate("(function(){var st=__DB.auction_state[0];var n=st.spin_pool.length,seg=360/n,idx=st.spin_pool.indexOf(st.spin_winner_id);var land=(-(idx+0.5+Number(st.spin_offset))*seg);return Math.abs(((land%360)+360)%360 - ((-(idx+0.5+Number(st.spin_offset))*seg%360)+360)%360)<1e-6 && Math.abs(Number(st.spin_offset))<=0.35;})()"))
    ok('admin: spin disabled while a player is on the block',adm.evaluate("document.getElementById('btn-spin').disabled")==True)
    # sell
    adm.fill('#sell-price','250');adm.click('#btn-sold');adm.wait_for_timeout(400)
    opts=adm.locator('#sell-team option').all_inner_texts()
    ok('team dropdown shows each team with its owner and points left',len(opts)==4 and any('Desi Steelers FC — Owner: Nasiq (200 pts left)'==o for o in opts),opts)
    adm.fill('#sell-price','');adm.type('#sell-price','1a2b-3.');ok('price field accepts digits only',adm.input_value('#sell-price')=='123',adm.input_value('#sell-price'))
    adm.fill('#sell-price','')
    ok('sell: over-budget rejected','Not enough points' in adm.inner_text('#sell-msg'))
    adm.fill('#sell-price','');adm.click('#btn-sold');adm.wait_for_timeout(300)
    ok('sell: empty price rejected','digits only' in adm.inner_text('#sell-msg'))
    adm.fill('#sell-price','75');adm.click('#btn-sold');adm.wait_for_timeout(800)
    rows=adm.evaluate("__DB.team_season_rosters")
    ok('sell: saved (price 75) and block cleared',len(rows)==5 and rows[-1]['auction_price']==75 and 'Waiting' in adm.inner_text('#on-block'))
    ok('sold player stays off the wheel (still 4)',adm.evaluate('wheelNames.length')==4)
    # ---- unsold -> round 2 ----
    adm.click('#btn-spin');adm.wait_for_timeout(6800);w2=adm.evaluate("__DB.auction_state[0].spin_winner_id")
    ok('2nd spin only from remaining 4',len(adm.evaluate("__DB.auction_state[0].spin_pool"))==4 and w2!=winner)
    adm.click('#btn-unsold');adm.wait_for_timeout(800)
    ok('unsold: goes to Round 2 list, removed from Round 1 wheel (3 left)',adm.evaluate("__DB.auction_unsold[0].round")==1 and adm.locator('#round2 .chip').count()==1 and adm.evaluate('wheelNames.length')==3,adm.evaluate('wheelNames'))
    # ---- finish round 1: sell/unsold the remaining 3 ----
    for i in range(3):
        adm.click('#btn-spin');adm.wait_for_timeout(6800)
        if i==0: adm.click('#btn-unsold')
        else:
            adm.fill('#sell-price','10');adm.click('#btn-sold')
        adm.wait_for_timeout(700)
    ok('round 1 exhausted: wheel empty and says Round 1 is complete',adm.evaluate('wheelNames.length')==0 and 'Round 1 is complete' in adm.inner_text('#wheel-empty'),adm.inner_text('#wheel-empty'))
    ok('admin: "Load Round 2 players" button appears (2 players unsold)',adm.is_visible('#btn-load-r2') and adm.locator('#round2 .chip').count()==2,adm.locator('#round2 .chip').count())
    adm.click('#btn-load-r2');adm.wait_for_timeout(800)
    ok('Round 2 loaded onto the wheel: exactly the unsold players',adm.evaluate('wheelRound()')==2 and adm.evaluate('wheelNames.length')==2 and 'round 2' in adm.inner_text('#wheel-round-label').lower(),adm.inner_text('#wheel-round-label'))
    sync(adm,vw);vw.wait_for_timeout(3000)
    ok('viewer also sees the Round 2 wheel (2 names)',vw.evaluate('wheelRound()')==2 and vw.evaluate('wheelNames.length')==2,(vw.evaluate('wheelRound()'),vw.evaluate('wheelNames')))
    ok('unsold button says final in Round 2','final' in adm.inner_text('#btn-unsold').lower())
    adm.click('#btn-spin');adm.wait_for_timeout(6800);adm.click('#btn-unsold');adm.wait_for_timeout(800)
    ok('round 2 unsold -> final unsold list, wheel down to 1',adm.evaluate("__DB.auction_unsold.filter(u=>u.round===2).length")==1 and adm.evaluate('wheelNames.length')==1 and 'Final unsold' in adm.inner_text('#round2'),adm.inner_text('#round2'))
    adm.click('#btn-spin');adm.wait_for_timeout(6800);adm.fill('#sell-price','5');adm.click('#btn-sold');adm.wait_for_timeout(800)
    ok('round 2 sale works; wheel empty afterwards',adm.evaluate('wheelNames.length')==0)
    # ---- put back + undo ----
    sb=Site(pw,scenario_auction(),admin=True);p=sb.page('auction.html',1200)
    p.click('#btn-spin');p.wait_for_timeout(6800);pid=p.evaluate("__DB.auction_state[0].current_player_id")
    p.click('#btn-putback');p.wait_for_timeout(800)
    ok('put back: player returns to wheel (5 names), block cleared',p.evaluate('wheelNames.length')==5 and 'Waiting' in p.inner_text('#on-block'))
    p.click('#btn-spin');p.wait_for_timeout(6800);p.fill('#sell-price','30');p.click('#btn-sold');p.wait_for_timeout(800)
    p.locator('[data-undo-sale]').first.click();p.wait_for_timeout(800)
    ok('undo sale: back on the wheel, budgets restored',p.evaluate('wheelNames.length')==5 and p.inner_text('#team-grid').count('200 pts left')==4,p.inner_text('#team-grid')[:100])
    p.click('#btn-spin');p.wait_for_timeout(6800);p.click('#btn-unsold');p.wait_for_timeout(800);p.click('#btn-undo-last');p.wait_for_timeout(800)
    ok('undo last action reverses unsold (back to 5 on wheel)',p.evaluate('wheelNames.length')==5 and len(p.evaluate("__DB.auction_unsold"))==0)
    ok('no JS errors in admin flows',not [e for e in p.errs+adm.errs if 'DIALOG' not in e],(p.errs,adm.errs))
    # ---- other pages reflect the sale ----
    d=scenario_auction();d['team_season_rosters'].append({'id':'rx','season_id':'season1','team_id':'t4','player_id':'p4','is_owner':False,'auction_price':60,'jersey_number':None,'sold_at':'2026-10-02T00:00:00Z'})
    s2=Site(pw,d)
    q=s2.page('player.html?id=p4');ok('player page: "sold for 60 pts"','sold for 60 pts' in q.inner_text('#player-team'))
    q=s2.page('team.html?id=t4');ok('team page: player in squad with price','Ayush' in q.inner_text('#roster-grid') and '60 pts' in q.inner_text('#roster-grid'))
    q=s2.page('teams.html');ok('teams page: 2 players, 140 pts left','2 players' in q.inner_text('#teams-grid') and '140 pts left' in q.inner_text('#teams-grid'))
print(f"\n{sum(R)} passed, {len(R)-sum(R)} failed")
